const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';
const ACTIVE_EMPLOYEE = 'ACTIVE_EMPLOYEE';
const NOT_ACTIVE_EMPLOYEE = 'NOT_ACTIVE_EMPLOYEE';

export { LOAD_EMPLOYEES, ACTIVE_EMPLOYEE, NOT_ACTIVE_EMPLOYEE };
